# Server configuration
server.port=8080
spring.application.name=api-gateway

# Simple route configuration to forward requests to services
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/users/**

spring.cloud.gateway.routes[1].id=project-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/projects/**,/api/tasks/**

# Exclusion
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# For development only
logging.level.org.springframework.cloud.gateway=DEBUG

# Swagger UI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Aggregate OpenAPI documentation
springdoc.swagger-ui.urls[0].name=Users
springdoc.swagger-ui.urls[0].url=/v3/api-docs/user-service
springdoc.swagger-ui.urls[1].name=Projects
springdoc.swagger-ui.urls[1].url=/v3/api-docs/project-service

# Security 
jwt.secret=${JWT_SECRET_KEY:6Jg16M0BZJ4pN5uWUj0PKoU3tz9VKmRuLl4voBFcTtQaRv1T3ANcb5Qn7OeQmr3YZfGGHc5qSs1hx9vZ2uGFfxyzHJKLMN5XCvBnQPrSt6U7Vw8XYZabcdeFgHijk}