spring.application.name=user-service
server.port=8081

# Temporarily disable database to allow startup
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# For development only
logging.level.com.specno=DEBUG

# Swagger UI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Security
jwt.secret=${JWT_SECRET_KEY:6Jg16M0BZJ4pN5uWUj0PKoU3tz9VKmRuLl4voBFcTtQaRv1T3ANcb5Qn7OeQmr3YZfGGHc5qSs1hx9vZ2uGFfxyzHJKLMN5XCvBnQPrSt6U7Vw8XYZabcdeFgHijk}
jwt.expiration=86400000

# spring.security.filter.order=10