spring.application.name=user-service
server.port=8081

# Temporarily disable database to allow startup
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# For development only
logging.level.com.specno=DEBUG