# Server configuration
server.port=8082
spring.application.name=project-service

# Exclusions
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Swagger UI Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

spring.security.filter.order=10

# For development only
logging.level.com.specno=DEBUG