# Server configuration
server.port=8082
spring.application.name=project-service

# Temporarily disable database to allow startup
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# For development only
logging.level.com.specno=DEBUG